[book]
authors = ["Ferrous Systems"]
language = "en"
multilingual = false
src = "src"
title = "Rust Training Slides by Ferrous Systems"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.playground]
copyable = false          # include the copy button for copying code snippets
